# Generated by Django 5.0.7 on 2024-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
