# Generated by Django 3.2.12 on 2024-08-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
    ]
