# Generated by Django 3.2.12 on 2024-07-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
            preserve_default=False,
        ),
    ]
