# Generated by Django 5.0.7 on 2024-08-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_profile',
            new_name='patient_profile',
        ),
    ]
