# Generated by Django 3.2.12 on 2024-08-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
