# Generated by Django 5.0.7 on 2024-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_doctors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
